### ISSUE TITLE
Browser Action : Link in popup does not redirect on click

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse-Presentation-Embed#22]
The Link in the Popup, when the Circuitverse Chrome Extension is clicked, does not performs any action. We need to Open in new tab by right clicking the link in order to view the Documentation.

Screenshot :

![image](https://user-images.githubusercontent.com/42182955/97472901-5d765600-1970-11eb-9f81-0401b59ec453.png)

**Comment by DevanshD3** [comment]
Is anyone working on this issue ? @Shivansh2407

**Comment by Shivansh2407** [comment]
Go ahead @DevanshD3 and make a PR👍

**Comment by ShreyaPrasad1209** [comment]
@Shivansh2407 @satu0king can we add this to good first issues?

**Comment by Shivansh2407** [comment]
Sure! @satu0king please add a good-first-issue label here. Thanks :+1:

**Comment by Jayita10** [comment]
Hi @Shivansh2407, can you please help me by providing the documentation link which should be open in nwe tab?

**Comment by Jayita10** [comment]
@Shivansh2407 can I work on this issue?

**Comment by ShreyaPrasad1209** [comment]
@Jayita10 sure

**Comment by Jayita10** [comment]
The link should be redirected to here-  https://docs.circuitverse.org/#/embedding_circuits?id=embedding-in-google-slides
right?

**Comment by Shivansh2407** [comment]
Yes @Jayita10 👍🏻

**Comment by Jayita10** [comment]
I have checked Chrome Extension/views/browser_action.html and the link pasted there is exactly same, I think the issue is solved. Please correct me if I miss something

> The link should be redirected to here- https://docs.circuitverse.org/#/embedding_circuits?id=embedding-in-google-slides
> right?

**Comment by Shivansh2407** [comment]
Hey @Jayita10, are you able to view the CV Docs page on clicking the link? Because recently when I checked, I was not redirected to the Docs page, instead on clicking the link, nothing happened. If it's working on your end, do let us know.

**Comment by Jayita10** [comment]
No it is not redirecting
How should I approach for this problem?

**Comment by Nonna-source** [comment]
I would love to try my hand at this issue.

**Comment by Palaksharma23** [comment]
I would love to work on this issue , can i take this up ?
